# NumPy is a Python library used for working with arrays. 
It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for Numerical Python.
In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [64]:
import numpy as np

In [25]:
l1=[1,2,3,4]

In [26]:
print(l1)


[1, 2, 3, 4]


# Create numpy array from a 1D list
1D array is a vector only
Check dimension and, shape, and size of the array

In [60]:
arr1=np.array(l1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)


(4,)
1
4


In [61]:
# Reshape an array from 1D to 2D

In [63]:
arr1=arr1.reshape((arr1.size,-1))
print(arr1.shape)
print(arr1.ndim)

(4, 1)
2


In [29]:
print(arr1)

[[1]
 [2]
 [3]
 [4]]


# Create numpy array from a 2D list
2D array is like matrix it has rows and columns
Check dimension and, shape, and size of the array

In [30]:
l2=[[1,2,3],[4,5,6]]

In [31]:
arr2=np.array(l2)

In [32]:
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


# Create numpy array from a 3D list
3D array is a three dimensional array
Check dimension and, shape, and size of the array

In [33]:
l3=[
    [[1,2,3,4,5],[9,6,4,2,1]],
    [[3,5,4,6,7],[2,2,2,2,2]],
    [[1,1,3,3,4],[8,9,8,9,8]]
]

In [34]:
print(l3)

[[[1, 2, 3, 4, 5], [9, 6, 4, 2, 1]], [[3, 5, 4, 6, 7], [2, 2, 2, 2, 2]], [[1, 1, 3, 3, 4], [8, 9, 8, 9, 8]]]


In [35]:
arr3=np.array(l3)

In [36]:
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

[[[1 2 3 4 5]
  [9 6 4 2 1]]

 [[3 5 4 6 7]
  [2 2 2 2 2]]

 [[1 1 3 3 4]
  [8 9 8 9 8]]]
(3, 2, 5)
3
30


# Create an array of zeros only

In [41]:
arr4=np.zeros(10)
print(arr4)
print(arr4.shape)
print(arr4.ndim)
arr4=arr4.reshape(2,-1)
print(arr4)
print(arr4.shape)
print(arr4.ndim)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)
2


# Create an array of ones only

In [42]:
arr4=np.ones(10)
print(arr4)
print(arr4.shape)
print(arr4.ndim)
arr4=arr4.reshape(2,-1)
print(arr4)
print(arr4.shape)
print(arr4.ndim)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
1
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
2


# Reshape multidimensional array to vector
It is called flatten the array

In [45]:
arr=arr4.reshape(-1)
print(arr)
arr=arr4.reshape(10,)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Create an array from another array with same value, size and dimension

In [43]:
arr5=np.array(arr4)
print(arr5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
arr6=arr4.copy()
print(arr6)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Slicing an array
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Slicing a one dimensional array

In [46]:
arr1=np.array([10,25,33,4,9,30,82,91,12])
print(arr1)
print(arr1[2:5])

[10 25 33  4  9 30 82 91 12]
[33  4  9]


# Slicing a two dimensional array

In [48]:
arr=np.array([[1,2,3,10,22,34],[4,5,6,10,21,67]])
print(arr)
print(arr[:,1:4])

[[ 1  2  3 10 22 34]
 [ 4  5  6 10 21 67]]
[[ 2  3 10]
 [ 5  6 10]]


In [49]:
print(arr[0:1,1:4])

[[ 2  3 10]]


In [50]:
print(arr[:,1:])

[[ 2  3 10 22 34]
 [ 5  6 10 21 67]]


In [51]:
print(arr[:,1:-1])

[[ 2  3 10 22]
 [ 5  6 10 21]]


# Slicing a three dimensional array

In [52]:
arr=np.array(l3)
print(arr)

[[[1 2 3 4 5]
  [9 6 4 2 1]]

 [[3 5 4 6 7]
  [2 2 2 2 2]]

 [[1 1 3 3 4]
  [8 9 8 9 8]]]


In [53]:
print(arr.shape)

(3, 2, 5)


In [54]:
print(arr[0:2,:,:])

[[[1 2 3 4 5]
  [9 6 4 2 1]]

 [[3 5 4 6 7]
  [2 2 2 2 2]]]


In [55]:
print(arr[0:2,:-1,:])

[[[1 2 3 4 5]]

 [[3 5 4 6 7]]]


In [56]:
print(arr[0:2,:,1:4])

[[[2 3 4]
  [6 4 2]]

 [[5 4 6]
  [2 2 2]]]
